// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;


public class ActionArenaSwaredList : LogicAction
{ 
    public override bool ProcessAction()
    { 
        List<ArenaRewaredViewData> list = new List<ArenaRewaredViewData>();
        //直接取值
        foreach (AranePointRewardData val in GameShared.Instance.aranePointRewardTable.Values)
        {
            ArenaRewaredViewData v = new ArenaRewaredViewData();
            v.desc = val.point.ToString();
            List<GameShared.StrData> ll = GameShared.Instance.GetStrData(val.reward);
            v.item1 = new ItemViewData();
            v.item1.data = GameShared.Instance.GetItemData(ll[0].id);
            v.item1.curCount = ll[0].num; 
            list.Add(v);
        }
        EventManager.Trigger<EventArenaRewardList>(new EventArenaRewardList(list));
        return true;
    }
}
