// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;


public class ActionArenaPointList : LogicAction
{ 
    public override bool ProcessAction()
    {
        List<AranePointViewData> list = new List<AranePointViewData>();
        //直接取值
        foreach (AranePointRewardData val in GameShared.Instance.aranePointRewardTable.Values)
        {
            AranePointViewData v = new AranePointViewData();
            v.num = val.point;
            List<GameShared.StrData>  ll= GameShared.Instance.GetStrData(val.reward);
            v.list = new List<ItemViewData>();
            for (int i = 0; i < ll.Count; i++)
            {

                ItemViewData d = new ItemViewData();
                d.data = GameShared.Instance.GetItemData(ll[i].id);
                d.curCount = ll[i].num;
                v.list.Add(d);
            }
            list.Add(v);
        }
        EventManager.Trigger<EventPointRewardList>(new EventPointRewardList(list)); 
        return true;
    }
}
